//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SampleAddin.rc 使用
//
#define IDR_NEX3DMODELINGTOOL           100
#define IDS_NAME                        101
#define IDS_CMD_STRING1                 102
#define IDS_CMD_STRING2                 103
#define IDS_CATEGORY_STRING             104
#define IDS_CATEGORY_STRING1            104
#define IDS_DESCRIPTION                 105
#define IDS_SAMPLECMD_STRING            106
#define IDS_CMD_STRING3                 107
#define IDS_CMD_STRING4                 108
#define IDS_CATEGORY_STRING2            109
#define IDS_COMMANDBAR_NAME1            110
#define IDS_COMMANDBAR_NAME2            111
#define IDS_CMD_STRING5                 112
#define IDS_CMD_STRING6                 113
#define IDS_CMD_STRING7                 114
#define IDS_COMMANDBAR_NAME3            115
#define IDS_MODELINGCHECKBAR            116
#define IDS_TITLE1                      117
#define IDS_TITLE2                      118
#define IDS_E_BAD_INTERNET_EXPLORER_VERSION 119
#define IDS_HELPFILENAME                120
#define IDS_SUMMARY                     121
#define IDS_SHORTCUT_CMD                122
#define IDS_CMD_SOLID_DEMO              123
#define IDR_TOOLBAR_MEDIUM              128
#define IDR_TOOLBAR_LARGE               129
#define IDR_TOOLBAR_LARGEMONOCHROME     130
#define IDR_TOOLBAR_MEDIUMMONOCHROME    131
#define IDD_DIALOG1                     132
#define IDD_EDGEBARDIALOG               133
#define IDB_EDGEBAR                     134
#define IDD_DIALOG2                     134
#define IDB_PNG1                        135
#define IDD_DIALOG3                     135
#define IDD_DIALOG4                     136
#define IDB_BITMAP1                     137
#define IDB_BITMAP2                     138
#define IDR_BIN2                        141
#define IDB_CHECK                       141
#define IDD_DIALOG5                     142
#define IDB_PNG2                        142
#define IDB_PNG3                        143
#define IDR_ZIPRES                      145
#define IDD_DIALOG6                     146
#define IDD_DLG_COMMON                  146
#define IDB_MODELINGCHECKBAR            147
#define IDC_TREECTRL                    150
#define IDC_LISTCTRL                    151
#define IDB_FOLDER_L                    152
#define IDB_FOLDER_S                    153
#define IDS_OK                          1000
#define IDS_CANCEL                      1001
#define IDC_TREE1                       1001
#define IDS_BUTTON1                     1002
#define IDC_TREE2                       1002
#define IDC_STATIC_NOTE                 1002
#define IDC_STATIC_DATANOTE             1002
#define IDS_LIST1                       1003
#define IDC_EDIT_DATAPATH               1003
#define IDC_BUTTON_BROWSER              1004
#define IDS_COMBO1                      1005
#define IDC_COMBO1                      1005
#define IDS_ANGLE                       1007
#define IDS_LENGTH                      1008
#define IDC_SLIDER1                     1009
#define IDC_RADIO1                      1010
#define IDC_CHECK1                      1011
#define IDC_STATIC13                    1012
#define IDC_EDIT1                       1013
#define IDC_BUTTON1                     1014
#define IDC_X                           1015
#define IDC_CHECK                       1020
#define IDC_EDIT2                       1021
#define IDS_CMD_CATEGORY                2000
#define IDS_CMD_GROUP_MODELTESTTOOLS    2001
#define IDS_CMD_DATABASECHECK           2002
#define IDB_DATABASECHECK               2003
#define IDS_CMD_MODELINGCHECK           2004
#define IDB_MODELINGCHECK               2005
#define IDS_CMD_PACKAGEMODELINGCHECK    2006
#define IDB_PACKAGEMODELINGCHECK        2007
#define IDD_DIALOG_PROGRESS             3000
#define IDC_PROGRESS_DLG                3001
#define IDC_STATIC1_DLG                 3002
#define IDC_STATIC2_DLG                 3003
#define IDD_DIALOG_WAIT                 3010
#define IDC_GIF_CONNECTING              3011
#define IDC_STATIC_WAIT                 3012
#define IDR_WAITING                     3013
#define IDD_VOLUMEEXTRACTIONPAGE        3020
#define IDC_LIST_SELECT_FACE            3021
#define IDC_LIST_SELECT_HOLES           3022
#define IDC_BUTTON_CLEAN_ALL_HOLES      3023
#define IDC_BUTTON_GET_INTERIOR_FACES   3024
#define IDC_BUTTON_PREVIEW              3025
#define IDC_BUTTON_ADD                  3025
#define IDC_SLIDER_HOLES                3026
#define IDS_PMP_CREATE_FLUID_ADD_FLUID_BODIES_TO_DOC 3030
#define IDS_PMP_CREATE_FLUID_CREATE_LEAK_TRACKING_FACES 3031
#define IDS_PMP_CREATE_FLUID_CLEANING_LEAK_TRACKING_FACES 3032
#define IDS_PMP_CREATE_FLUID_CREATE_INTERIOR_BODIES 3033
#define IDS_PMP_CREATE_FLUID_CREATE_PREVIEW_INTERIOR_BODIES 3034
#define IDS_PMP_CREATE_FLUID_CLEAN_PREVIEW_INTERIOR_BODIES 3035
#define IDS_PMP_START_SELECT_INTERIOR_FACE_TIP 3036
#define IDS_PMP_START_SELECT_INTERIOR_FACE_CAPTION 3037
#define IDS_PMP_UN_START_SELECT_INTERIOR_FACE_CAPTION 3038
#define IDS_PMP_CHECK_UNPREVIEW_CAPTION 3039
#define IDS_PMP_CHECK_PREVIEW_CAPTION   3040
#define IDS_PMP_CREATE_FLUID_SET_ATTRIBUTE_ERROR 3041
#define IDS_PMP_TITLE                   3042
#define IDS_STRING_FIND_INTERIOR_FACES_WAITING 3043
#define IDS_PMP_CREATE_FLUID_CREATE_FLUID_BOIDES_FEATURE 3044
#define PMP_CREATE_FLUID_CREATE_INTERIOR_FACES 3045
#define PMP_CREATE_FLUID_FIND_BOUNDARY_EDGES_IN_MERGE_BODY 3046
#define PMP_CREATE_FLUID_FIND_INTERIOR_CONNECTED_FACES 3047
#define PMP_CREATE_FLUID_COMPUTE_MERGE_AND_SEPARATE_BODIES 3048
#define PMP_CREATE_FLUID_VOLUME_EXTRACTION_RESULTINFOMESSAGE 3049
#define PMP_CREATE_FLUID_FIND_EXTERNAL_CAP_FACES 3050
#define IDS_PMP_CREATE_FLUID_CREATE_OUTERIOR_LEAK_TRACKING_FACES 3051
#define IDS_PMP_CREATE_FLUID_CREATE_INTERIOR_LEAK_TRACKING_FACES 3052
#define IDS_PMP_AUTOMATIC_FIND_CAPFACES_TIP 3053
#define IDS_PMP_CREATE_FLUID_SET_ATTRIBUTE_FOR_FACES 3054
#define IDS_CMD_DRAW_BOX                3055
#define IDS_CMD_SKETCH_DEMO             3056
#define IDS_CMD_BN1                     3057
#define IDS_CMD_BN2                     3058
#define IDS_CMD_BN3                     3059
#define IDS_STRING3060                  3060
#define IDS_CMD_BN4                     3060
#define IDS_CMD_BN5                     3061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           1076
#endif
#endif
